### ISSUE TITLE
请教。

### ISSUE THREAD

**Issue by ylmyg** [OnexZgj/flutter_onex#1]
到底该怎么去学Flutter呢？我学了几天了，都还不是很上手，觉得很别捏，各种不习惯。

**Comment by OnexZgj** [comment]
这种按照个人学习习惯了，分享一下我的过程，先学了一下dart语言，网上资源也比较多，然后尝试写简单的组件，然后是列表，再进行网络请求和处理，其他的我也刚刚接触，希望能帮到你
